##################################################################
# Standardized Terraform-Docs Configuration                     #
# ============================================================== #
# Organization: grinntec-terraform-modules-azure                #
# Purpose: Central configuration for all Terraform modules      #
# Version: 1.0                                                  #
##################################################################

formatter: "markdown table"     # Format as Markdown document

version: ""                     # See .github\.github\actions\terraform-docs\action.yaml for supported versions

header-from: main.tf
footer-from: ""

recursive:                      # Documentation for main module and its submodules can be generated all in one execution
  enabled: false
  path: ""                      # Path to find submodules

sections:                       # Specify at a granular level what sections to hide/show
  hide: []
  show: []

content: |-

  🏗️ {{ if .Module.Resources }}{{ with index .Module.Resources 0 }}{{ .Type | title | replace "_" " " }}{{ end }} Module{{ else }}Terraform Azure Module{{ end }}

  # {{ .Header }}

  > **Enterprise Terraform Module for Azure Infrastructure**  
  > Part of the [grinntec-terraform-modules-azure](https://github.com/grinntec-terraform-modules-azure) collection

  ## Overview

  This Terraform module provides a standardized, production-ready implementation following infrastructure as code best practices. Each module in our collection is designed for consistency, security, and maintainability across enterprise Azure deployments.

  ## 📁 Repository Structure

  | File/Directory | Purpose | Description |
  |---------------|---------|-------------|
  | **main.tf** | Core Resources | Primary resource definitions and module logic |
  | **variables.tf** | Input Interface | Variable declarations with validation and documentation |
  | **outputs.tf** | Output Interface | Module outputs for downstream consumption |
  | **locals.tf** | Local Values | Computed values and naming conventions |
  | **data.tf** | Data Sources | External data lookups and references |
  | **versions.tf** | Version Control | Terraform and provider version constraints |
  | **example/** | Usage Examples | Working examples demonstrating module usage |
  | **tf-management/** | Quality Tools | Automated testing, linting, and documentation |

  {{ .Header }}
  
  ## 📊 Module Documentation

  {{ .Resources }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  
  ---

  ## 💡 Usage Examples

  ### Production Deployment Example
  
  ```hcl
  {{ include "example/main-production.tf" }}
  ```

  ---
   
  ## 🔍 Quality Assurance

  ### TFLint Results
  
  ```text
  {{ include "tf-management/tf-lint/results/tf-lint-results-module.txt" }}
  ```
  
  ---

  ## Security Scan Results (Checkov)
 
  ```text
  {{ include "tf-management/checkov/module/results_cli.txt" }}
  ```

  ---

  ## 📞 Support & Contributing

  - 📚 **Documentation**: [Terraform Module Standards](https://github.com/grinntec-terraform-modules-azure/.github)
  - 🐛 **Issues**: Report issues in this repository's issue tracker
  - 💡 **Discussions**: Use GitHub Discussions for questions and ideas
  - 🤝 **Contributing**: See [CONTRIBUTING.md](CONTRIBUTING.md)

  ### Module Versioning
  This module uses [Semantic Versioning](https://semver.org/). Always pin to a specific version in production:
  ```hcl
  source = "git::https://github.com/grinntec-terraform-modules-azure/[MODULE-NAME].git?ref=v1.0.0"
  ```

  ---

  > This documentation was automatically generated using [terraform-docs](https://terraform-docs.io/)
  
  {{ .Footer }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true