# Central Terraform-Docs Configuration
# Used by all Terraform modules in grinntec-terraform-modules-azure
formatter: "markdown table"

header-from: main.tf
footer-from: ""

content: |-
  {{ .Header }}
  
  {{ .Resources }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  
  # Deployment Example
  
  ```hcl
  {{ include "example/main-production.tf" }}
  ```
  
  ---
   
  # TFLint Results
  
  ```text
  {{ include "tf-management/tf-lint/results/tf-lint-results-module.txt" }}
  ```
  
  ---

  # Security Scan Results
 
  ```text
  {{ include "tf-management/checkov/module/results_cli.txt" }}
  ```
  
  {{ .Footer }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true