name: Terraform Module Governance

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '!tf-management/**'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '!tf-management/**'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  terraform-governance:
    runs-on: ubuntu-latest
    name: 🚀 Terraform Module Governance

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: 💾 Cache Terraform providers
        uses: grinntec-terraform-modules-azure/.github/.github/actions/cache-terraform-providers@main

      - name: 🔧 Format Terraform files
        uses: grinntec-terraform-modules-azure/.github/.github/actions/terraform-fmt@main

      - name: ✅ Validate Terraform configuration
        uses: grinntec-terraform-modules-azure/.github/.github/actions/terraform-validate@main

      - name: 🔍 Run TF-Lint
        uses: grinntec-terraform-modules-azure/.github/.github/actions/tf-lint@main

      - name: 🛡️ Security scan with Checkov
        uses: grinntec-terraform-modules-azure/.github/.github/actions/terraform-security-scan@main

      - name: 📚 Generate documentation
        uses: grinntec-terraform-modules-azure/.github/.github/actions/terraform-docs@main
        with:
          config_file: './tf-management/tf-docs/tf-docs.yaml'

      - name: 📤 Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add README.md || true
          git add tf-management/tf-lint/results/ || true
          git add tf-management/checkov/module/ || true
          git add "*.tf" || true
          
          if [[ $(git status --porcelain) ]]; then
            git commit -m "docs: update terraform documentation and formatting [skip ci]"
            git push
            echo "✅ Changes committed and pushed"
          else
            echo "✅ No changes to commit"
          fi
        shell: bash