name: Update README with Info Badges
description: Extracts the required data and updates the README with relevant info badges.

inputs:
  working_directory:
    description: 'Working directory for Terraform files'
    required: false
    default: '.'

runs:
  using: composite
  steps:

    - name: Get Latest Release Tag
      id: get_tag
      shell: bash
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "unreleased")
        if [ -z "$TAG" ]; then
          TAG="unreleased"
        fi
        echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Update README Badges Top Row
      shell: bash
      run: |
        README_PATH="${{ github.workspace }}/README.md"
        TAG="${{ steps.get_tag.outputs.latest_tag }}"
        # Release badge
        RELEASE_BADGE="![Release](https://img.shields.io/badge/release-$TAG-blue.svg)"
        # TFLint badge
        TFLINT_RESULT_FILE="tf-management/tf-lint/results/tf-lint-results-module.txt"
        TFLINT_BADGE_GREEN='![TFLint](https://img.shields.io/badge/tflint-passing-brightgreen.svg)'
        TFLINT_BADGE_YELLOW='![TFLint](https://img.shields.io/badge/tflint-issues-yellow.svg)'
        TFLINT_BADGE="$TFLINT_BADGE_YELLOW"
        if [[ -f "$TFLINT_RESULT_FILE" ]]; then
          if grep -q 'Analysis Status: PASSED' "$TFLINT_RESULT_FILE"; then
            TFLINT_BADGE="$TFLINT_BADGE_GREEN"
          fi
        fi
        # Checkov badge
        CHECKOV_RESULT_FILE="tf-management/checkov/module/results_cli.txt"
        CHECKOV_BADGE_GREEN='![Checkov](https://img.shields.io/badge/checkov-passing-brightgreen.svg)'
        CHECKOV_BADGE_YELLOW='![Checkov](https://img.shields.io/badge/checkov-issues-yellow.svg)'
        CHECKOV_BADGE="$CHECKOV_BADGE_YELLOW"
        if [[ -f "$CHECKOV_RESULT_FILE" ]]; then
          FAILED_CHECKS=$(grep 'Failed checks:' "$CHECKOV_RESULT_FILE" | awk -F': ' '{print $2}' | tr -d ' ')
          if [[ "$FAILED_CHECKS" == "0" ]]; then
            CHECKOV_BADGE="$CHECKOV_BADGE_GREEN"
          fi
        fi
        # Remove any existing badges
        sed -i '/!\[Release](https:\/\/img.shields.io\/badge\/release-/d' "$README_PATH"
        sed -i '/!\[TFLint](https:\/\/img.shields.io\/badge\/tflint-/d' "$README_PATH"
        sed -i '/!\[Checkov](https:\/\/img.shields.io\/badge\/checkov-/d' "$README_PATH"
        # Insert all badges on the top row
        BADGE_ROW="$RELEASE_BADGE $CHECKOV_BADGE $TFLINT_BADGE"
        sed -i "1i$BADGE_ROW\n" "$README_PATH"
        echo "Updated README with badges: $BADGE_ROW"

    - name: Auto-commit README Update
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs: update README with release version ${{ steps.get_tag.outputs.latest_tag }}"
        name: 'Update README with Release Version'
        commit_options: '--no-verify'