name: 'Update README with Release Version'
description: 'Dynamically update the README with the latest release version after governance workflow runs.'
runs:
  using: 'composite'
  steps:
    - name: Get Latest Release Tag
      id: get_tag
      shell: bash
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Update README with Release Version
      shell: bash
      run: |
        README_PATH="${{ github.workspace }}/README.md"
        TAG="${{ steps.get_tag.outputs.latest_tag }}"
        # Insert or update the release version at the top of README
        BADGE="![Release](https://img.shields.io/badge/release-$TAG-blue.svg)"
        # Remove any existing release badge
        sed -i '/^![Release](https:\/\/img.shields.io\/badge\/release-/d' "$README_PATH"
        # Insert badge at the top
        sed -i "1i$BADGE\n" "$README_PATH"
        echo "Updated README with release badge: $BADGE"

    - name: Auto-commit README Update
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs: update README with release version ${{ steps.get_tag.outputs.latest_tag }}"
        file_pattern: "README.md"
        commit_options: '--no-verify'
        skip_dirty_check: false
