name: Terraform Module Governance

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  terraform-governance:
    uses: grinntec-terraform-modules-azure/.github/.github/workflows/terraform-module-governance.yml@main
    with:
      terraform_version: 'latest'
      enable_security_scan: true
      enable_documentation: true
      auto_commit: true
      tf_docs_config: './tf-management/tf-docs/tf-docs.yaml'