name: 'Debug - Show Terraform Version'
description: 'Show and summarize the Terraform version used in the workflow.'
runs:
  using: 'composite'
  steps:
    - name: Debug - Show Terraform Version
      shell: bash
      run: |
        echo "::debug::Terraform setup complete"
        echo "::debug::Extracted version: ${{ steps.tf-version.outputs.terraform-version }}"
        echo "::group::Terraform Version Information"
        terraform version
        echo "::endgroup::"
        # Extract version info
        TF_VERSION=$(terraform version -json | jq -r '.terraform_version')
        echo "::notice::Using Terraform version: $TF_VERSION"
        # Write to job summary
        {
          echo "## Terraform Version Information"
          echo "- **Extracted from versions.tf**: \`${{ steps.tf-version.outputs.terraform-version }}\`"
          echo "- **Version Used**: \`$TF_VERSION\`"
          echo ""
          echo "### Version Details"
          echo '```'
          terraform version
          echo '```'
          echo ""
          echo "Reference: https://github.com/hashicorp/terraform/releases"
          echo ""
        } >> $GITHUB_STEP_SUMMARY
